- name: Install docker package and enable service
  hosts: 192.168.0.102
  tasks:
     - name: Docker package
       package:
          name: "docker-ce-18.06.3.ce-3.el7.x86_64"
          state: present
     - name: Docker service start and making permanent
       service:
          name: "docker"
          state: started
          enabled: yes
